export type ProjectCategory =
  | "fotovoltaika"
  | "elektroinstalace"
  | "hromosvody"
  | "kotelny"
  | "rekuperace"
  | "klimatizace"
  | "revize";

export const CATEGORY_LABELS: Record<ProjectCategory, string> = {
  fotovoltaika: "Fotovoltaika",
  elektroinstalace: "Elektroinstalace",
  hromosvody: "Hromosvody",
  kotelny: "Kotelny a tepelná čerpadla",
  rekuperace: "Rekuperace",
  klimatizace: "Klimatizace a chlazení",
  revize: "Revize a diagnostika",
};

export type Project = {
  id: string;
  title: string;
  place: string;
  /** ISO měsíc realizace, slouží k řazení. */
  date: string;
  dateLabel: string;
  category: ProjectCategory;
  image: string;
  /** Popis toho, co je na fotografii skutečně vidět. */
  alt: string;
};

export const PROJECTS: Project[] = [
  {
    id: "p01",
    title: "Kompletní rekonstrukce elektroinstalace bytu",
    place: "Písek",
    date: "2025-10",
    dateLabel: "říjen 2025",
    category: "elektroinstalace",
    image: "/reference/p01.jpg",
    alt: "Otevřený bytový rozvaděč po rekonstrukci s novou řadou jističů, proudových chráničů a značených vodičů, Písek",
  },
  {
    id: "p02",
    title: "Fotovoltaická elektrárna na rodinném domě s autodílnou",
    place: "Blatná",
    date: "2025-11",
    dateLabel: "listopad 2025",
    category: "fotovoltaika",
    image: "/reference/p02.jpg",
    alt: "Fotovoltaické panely na tmavé taškové střeše rodinného domu, pohled podél řady panelů za soumraku, Blatná",
  },
  {
    id: "p03",
    title: "Instalace tepelného čerpadla HotJet",
    place: "Blatná",
    date: "2025-11",
    dateLabel: "listopad 2025",
    category: "kotelny",
    image: "/reference/p03.jpg",
    alt: "Venkovní jednotka tepelného čerpadla HotJet postavená na betonových patkách u fasády rodinného domu, Blatná",
  },
  {
    id: "p04",
    title: "Rekuperace Zehnder v novostavbě rodinného domu",
    place: "Oldřichov u Písku",
    date: "2025-11",
    dateLabel: "listopad 2025",
    category: "rekuperace",
    image: "/reference/p04.jpg",
    alt: "Bílé flexibilní rozvody rekuperace vedené mezi krokvemi krovu novostavby, u nich červený kruhový odvodní ventil",
  },
  {
    id: "p05",
    title: "Rozvodna distribučního centra Billa",
    place: "Uničov",
    date: "2025-10",
    dateLabel: "říjen 2025",
    category: "elektroinstalace",
    image: "/reference/p05.jpg",
    alt: "Vysoká rozvaděčová skříň s několika řadami jističů a svázanými vodiči v rozvodně distribučního centra, Uničov",
  },
  {
    id: "p06",
    title: "Klimatizace Daikin",
    place: "Vimperk",
    date: "2025-10",
    dateLabel: "říjen 2025",
    category: "klimatizace",
    image: "/reference/p06.jpg",
    alt: "Dva technici na hliníkovém lešení osazují venkovní jednotku klimatizace Daikin na fasádu domu, Vimperk",
  },
  {
    id: "p07",
    title: "Fotovoltaická elektrárna",
    place: "Zvíkovské Podhradí",
    date: "2024-06",
    dateLabel: "červen 2024",
    category: "fotovoltaika",
    image: "/reference/p07.jpg",
    alt: "Pohled z výšky na rodinný dům s fotovoltaickými panely na taškové střeše uprostřed obce, Zvíkovské Podhradí",
  },
  {
    id: "p08",
    title: "Hromosvod na domě s fotovoltaikou",
    place: "Střelské Hoštice",
    date: "2025-04",
    dateLabel: "duben 2025",
    category: "hromosvody",
    image: "/reference/p08.jpg",
    alt: "Rodinný dům s červenou střechou, na hřebeni dvě jímací tyče hromosvodu, pod nimi pole fotovoltaických panelů, Střelské Hoštice",
  },
  {
    id: "p09",
    title: "Fotovoltaická elektrárna",
    place: "Smetanova Lhota",
    date: "2025-05",
    dateLabel: "květen 2025",
    category: "fotovoltaika",
    image: "/reference/p09.jpg",
    alt: "Detail černých fotovoltaických panelů na střeše rodinného domu, v pozadí zahrada a sousední stavení, Smetanova Lhota",
  },
  {
    id: "p10",
    title: "Řízení přetoků fotovoltaiky do bojleru",
    place: "Čimelice",
    date: "2025-07",
    dateLabel: "červenec 2025",
    category: "fotovoltaika",
    image: "/reference/p10.jpg",
    alt: "Zapojený adapter box SolaX s červenými a černými stejnosměrnými vodiči pro řízení přetoků do bojleru, Čimelice",
  },
  {
    id: "p11",
    title: "Analýza fotovoltaické elektrárny termokamerou",
    place: "Číčenice",
    date: "2024-10",
    dateLabel: "říjen 2024",
    category: "revize",
    image: "/reference/p11.jpg",
    alt: "Termokamerový snímek fotovoltaického pole s barevnou teplotní škálou a odečteným horkým místem 65,3 stupně Celsia, Číčenice",
  },
  {
    id: "p12",
    title: "Fotovoltaický ohřev vody",
    place: "Klínovice",
    date: "2025-09",
    dateLabel: "září 2025",
    category: "fotovoltaika",
    image: "/reference/p12.jpg",
    alt: "Malý nástěnný rozvaděč fotovoltaického ohřevu vody s jističi, přepěťovou ochranou a kabelovou vývodkou, Klínovice",
  },
  {
    id: "p13",
    title: "Fotovoltaická elektrárna",
    place: "Zadní Zborovice",
    date: "2025-05",
    dateLabel: "květen 2025",
    category: "fotovoltaika",
    image: "/reference/p13.jpg",
    alt: "Červená tašková střecha rodinného domu s fotovoltaickými panely mezi střešními okny, Zadní Zborovice",
  },
  {
    id: "p14",
    title: "Osvětlení v mostní konstrukci dálnice D4",
    place: "Nerestce",
    date: "2024-12",
    dateLabel: "prosinec 2024",
    category: "elektroinstalace",
    image: "/reference/p14.jpg",
    alt: "Rozsvícené svítidlo uvnitř betonové komory mostní konstrukce dálnice D4, podél stropu vede technologické potrubí",
  },
  {
    id: "p15",
    title: "Rozšíření fotovoltaické elektrárny",
    place: "Mutěnice",
    date: "2025-03",
    dateLabel: "březen 2025",
    category: "fotovoltaika",
    image: "/reference/p15.jpg",
    alt: "Rozšířené pole fotovoltaických panelů na střeše žlutého patrového rodinného domu, Mutěnice",
  },
  {
    id: "p16",
    title: "Hromosvod rodinného domu",
    place: "Topělec",
    date: "2025-08",
    dateLabel: "srpen 2025",
    category: "hromosvody",
    image: "/reference/p16.jpg",
    alt: "Rodinný dům s dokončeným hromosvodem, jímací vedení po hřebeni střechy a svod podél rohu fasády, Topělec",
  },
  {
    id: "p17",
    title: "Výměna hlavního rozvaděče",
    place: "Vodňany",
    date: "2025-06",
    dateLabel: "červen 2025",
    category: "elektroinstalace",
    image: "/reference/p17.jpg",
    alt: "Nová plechová elektroměrová skříň s osazeným elektroměrem a hlavním jističem po výměně, Vodňany",
  },
  {
    id: "p18",
    title: "Nabíjecí stanice wallbox Solax",
    place: "Blatná",
    date: "2025-04",
    dateLabel: "duben 2025",
    category: "elektroinstalace",
    image: "/reference/p18.jpg",
    alt: "Světle modrá nabíjecí stanice wallbox Solax se zavěšeným nabíjecím kabelem na dřevěné stěně přístřešku, Blatná",
  },
  {
    id: "p19",
    title: "Chladicí jednotky v průmyslovém areálu",
    place: "Horažďovice",
    date: "2025-05",
    dateLabel: "květen 2025",
    category: "klimatizace",
    image: "/reference/p19.jpg",
    alt: "Otevřená chladicí jednotka u haly s viditelným vedením chladiva a servisním žebříkem, průmyslový areál Horažďovice",
  },
  {
    id: "p20",
    title: "Výměna rozvaděčů v průmyslovém areálu",
    place: "Strakonice",
    date: "2025-05",
    dateLabel: "květen 2025",
    category: "elektroinstalace",
    image: "/reference/p20.jpg",
    alt: "Technická místnost s vyměněnými rozvaděči, výstražným značením a podlahovým roštem, průmyslový areál Strakonice",
  },
  {
    id: "p21",
    title: "Hromosvod rodinného domu",
    place: "Bílsko",
    date: "2025-07",
    dateLabel: "červenec 2025",
    category: "hromosvody",
    image: "/reference/p21.jpg",
    alt: "Rodinný dům v lešení během rekonstrukce střechy s nataženým jímacím vedením hromosvodu, Bílsko",
  },
  {
    id: "p22",
    title: "Klimatizace multisplit",
    place: "Blatná",
    date: "2025-08",
    dateLabel: "srpen 2025",
    category: "klimatizace",
    image: "/reference/p22.jpg",
    alt: "Venkovní jednotka klimatizace Toshiba multisplit osazená na konzolách na fasádě domu, Blatná",
  },
  {
    id: "p23",
    title: "Fotovoltaická elektrárna",
    place: "Kozlov",
    date: "2025-07",
    dateLabel: "červenec 2025",
    category: "fotovoltaika",
    image: "/reference/p23.jpg",
    alt: "Souvislé pole fotovoltaických panelů na červené taškové střeše podélného rodinného domu, Kozlov",
  },
  {
    id: "p24",
    title: "Fotovoltaická elektrárna",
    place: "Dmýštice",
    date: "2025-05",
    dateLabel: "květen 2025",
    category: "fotovoltaika",
    image: "/reference/p24.jpg",
    alt: "Dvě pole fotovoltaických panelů na tmavé střeše rodinného domu s dřevěným vstupním přístřeškem, Dmýštice",
  },
  {
    id: "p25",
    title: "Fotovoltaická elektrárna",
    place: "Doksy",
    date: "2025-06",
    dateLabel: "červen 2025",
    category: "fotovoltaika",
    image: "/reference/p25.jpg",
    alt: "Fotovoltaické panely a střešní okna na červené střeše rodinného domu, před domem zahrada se stromem, Doksy",
  },
  {
    id: "p26",
    title: "Fotovoltaika s bateriovým úložištěm",
    place: "Rakovice",
    date: "2025-09",
    dateLabel: "září 2025",
    category: "fotovoltaika",
    image: "/reference/p26.jpg",
    alt: "Nástěnný střídač SolaX a pod ním dvojice bateriových modulů v bílé technické místnosti, Rakovice",
  },
  {
    id: "p27",
    title: "Úprava výrobní haly",
    place: "České Budějovice",
    date: "2025-09",
    dateLabel: "září 2025",
    category: "elektroinstalace",
    image: "/reference/p27.jpg",
    alt: "Vyklizená výrobní hala s novým řadovým osvětlením pod stropem a zaparkovanou dodávkou OK electric, České Budějovice",
  },
];

export const PROJECTS_SORTED = [...PROJECTS].sort((a, b) => b.date.localeCompare(a.date));

export function projectsByCategory(...cats: ProjectCategory[]) {
  return PROJECTS_SORTED.filter((p) => cats.includes(p.category));
}
